unbind C-b
set-option -g prefix C-a
#set -g prefix C-a
bind C-a send-prefix


# split panes using | and -
bind | split-window -h
bind _ split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf; display-message "~/.tmux.conf reloaded."

# switch panes using Alt-arrow without prefix
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

# switch windows using Shift-arrow without prefix
#bind -n S-Left previous-window
#bind -n S-Right next-window

# rename window to reflect current program
setw -g automatic-rename on
# renumber windows when a window is closed
set -g renumber-windows on

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# window status
setw -g window-status-format " #F#I:#W#F "
setw -g window-status-current-format " #F#I:#W#F "
#setw -g window-status-format "#[fg=magenta]#[bg=black] #I #[bg=cyan]#[fg=colour8] #W #(sysctl vm.loadavg)"
#setw -g window-status-current-format "#[bg=brightmagenta]#[fg=colour8] #I #[fg=colour8]#[bg=colour14] #W "
#setw -g window-status-current-bg colour0
#setw -g window-status-current-fg colour11
#setw -g window-status-current-attr dim
#setw -g window-status-bg green
#setw -g window-status-fg black
#setw -g window-status-attr reverse

#setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

#setw status-style bg=grey
#setw status-left "#(sysctl vm.loadavg)"

set -g mouse on
set -g history-limit 30000

# title
set -g set-titles on
set -g set-titles-string "#T"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'jaclu/tmux-menus'
set -g @menus_trigger 'Space'

run '~/.tmux/plugins/tpm/tpm'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
