#!/bin/bash

# User settings
~/.config/dconf/settings/dconf_inject.sh

systemctl --user enable systemd-tmpfiles-setup.service systemd-tmpfiles-clean.timer
systemctl --user enable --now backup-wallpapers.timer
systemctl --user enable --now cache_clean.timer
