# Fuzzel Configuration - Glassy Dark Theme

[main]
font=Liberation mono:weight=bold:size=12
dpi-aware=auto
prompt="❯ "
icon-theme=Adwaita
width=35
horizontal-pad=20
vertical-pad=15
inner-pad=5
line-height=20
lines=10
letter-spacing=0
anchor=center
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=0a0a0fe6
text=f8f8f2ff
match=8be9fdff
selection=8be9fdff
selection-text=0a0a0fff
selection-match=0a0a0fff
# border=8be9fdff

[border]
width=1
radius=15
selection-radius=8
[dmenu]
mode=text  # text | index
exit-immediately-if-empty=no
