#!/bin/env bash

EXPORT_FILE=~/.config/packages.lst##hostname.$(uname -n)
echo "${EXPORT_FILE}"

export_pacman() {
	command -v pacman || return
	
	echo "[pacman-explicit]" > "${EXPORT_FILE}"
	# shellcheck disable=SC2129
	pacman -Qte | awk '{ print $1 }' >> "${EXPORT_FILE}"

	echo -e "\n[pacman-deps]" >> "${EXPORT_FILE}"
	pacman -Qtd | awk '{ print $1 }' >> "${EXPORT_FILE}"
}

export_stew() {
	command -v stew || return
	
	echo -e "\n[stew]" >> "${EXPORT_FILE}"
	stew ls --tags >> "${EXPORT_FILE}"
}

export_fisher() {
    local PLUGINS="${HOME}/.config/fish/fish_plugins"

    [[ ! -f $PLUGINS ]] && return
    
	echo -e "\n[fisher]" >> "${EXPORT_FILE}"
	sort "${PLUGINS}" >> "${EXPORT_FILE}"
}

export_gox() {
	command -v gox || return
	
	echo -e "\n[gox]" >> "${EXPORT_FILE}"
	gox list >> "${EXPORT_FILE}"
}

export_aqua() {
	command -v aqua || return
	
	echo -e "\n[aqua]" >> "${EXPORT_FILE}"
	aqua list -i -a | awk '{ print $1" "$2 }' >> "${EXPORT_FILE}"
}
 
export_pacman
export_stew
export_fisher
export_gox
export_aqua






# yadm add "${EXPORT_FILE}"
# yadm commit -m "chore: update packages list"
