#!/bin/bash

# Installation paquets utiles
sudo pacman -S otf-fira-mono otf-fira-code fish adapta-gtk-theme arc-gtk-theme


# Maintenance
systemctl --user enable systemd-tmpfiles-setup.service systemd-tmpfiles-clean.timer
