name: actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    name: Run Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
